In [1]:
import numpy as np

#### Matrix(행렬) 표기법

- Matrix
$$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix}=\begin{pmatrix} 25 \\ 64 \end{pmatrix}$$

- Vector
  - 행(row vector) 또는 열(column vector)의 수가 1인 경우

- 역행렬(Inverse)
  - 아래를 만족할 때, B는 A의 역행렬이고 A는 B의 역행렬임
  - AB = BA = E(단위 행렬) 

#### numpy.linalg.inv
- 역행렬을 구할 때 사용하는 함수
- 모든 차원의 값이 같아야함(정방향이 되어야함)

In [10]:
x = np.random.rand(3, 3)
print(x)

y = np.linalg.inv(x)
print(y)

[[0.46811583 0.28425562 0.970313  ]
 [0.27359831 0.73209798 0.69682595]
 [0.67248905 0.10531768 0.35724151]]
[[-0.73421531 -0.00251001  1.99911737]
 [-1.44724784  1.89378154  0.2369469 ]
 [ 1.8087835  -0.55357711 -1.03386431]]


In [16]:
x @ np.linalg.inv(x)        # 행렬과 역행렬을 곱함 = 단위행렬(항등행렬) 

array([[ 1.00000000e+00, -9.20216187e-17,  6.41177048e-17],
       [ 1.51227489e-16,  1.00000000e+00,  5.09239522e-17],
       [-3.69612815e-17, -3.78948416e-18,  1.00000000e+00]])

In [18]:
np.matmul(x, np.linalg.inv(x))    # 행렬과 역행렬을 곱함 

array([[ 1.00000000e+00, -9.20216187e-17,  6.41177048e-17],
       [ 1.51227489e-16,  1.00000000e+00,  5.09239522e-17],
       [-3.69612815e-17, -3.78948416e-18,  1.00000000e+00]])

In [21]:
x = np.random.rand(3, 3, 3)     # 정사각행렬만 가능함(차원만 늘림)
print(x)

np.linalg.inv(x)

[[[0.32674666 0.54873703 0.41833658]
  [0.37103628 0.23697914 0.39349845]
  [0.43827265 0.08740093 0.01606599]]

 [[0.86829738 0.85474792 0.42237649]
  [0.76279912 0.78339169 0.20356142]
  [0.93974992 0.31092689 0.27713723]]

 [[0.22642928 0.44778435 0.50565105]
  [0.63798376 0.36550389 0.91952566]
  [0.17497497 0.13375637 0.67389607]]]


array([[[-0.59402343,  0.53890674,  2.26831679],
        [ 3.23376159, -3.45900868,  0.5174791 ],
        [-1.38737466,  4.11630317, -2.4504787 ]],

       [[-1.62939029,  1.11816072,  1.66199887],
        [ 0.21295795,  1.65562394, -1.54064319],
        [ 5.28620798, -5.64907664, -0.29889849]],

       [[-1.50871037,  2.86434203, -2.77632574],
        [ 3.2914952 , -0.78437686, -1.39946409],
        [-0.26157136, -0.58803244,  2.48254119]]])

In [23]:
np.matmul(x, np.linalg.inv(x))

array([[[ 1.00000000e+00, -3.37513568e-17,  9.21746554e-17],
        [-8.16184959e-17,  1.00000000e+00, -9.09799945e-17],
        [-1.35970237e-17, -4.67504265e-17,  1.00000000e+00]],

       [[ 1.00000000e+00, -1.41387766e-16,  1.31870745e-16],
        [-1.77703309e-17,  1.00000000e+00,  1.32077957e-16],
        [ 5.24172242e-17, -2.38113165e-16,  1.00000000e+00]],

       [[ 1.00000000e+00,  6.29676652e-17, -1.56693841e-16],
        [ 1.51418574e-16,  1.00000000e+00,  2.55858374e-16],
        [ 2.30220785e-17,  5.43123274e-17,  1.00000000e+00]]])

In [24]:
x @ np.linalg.inv(x)

array([[[ 1.00000000e+00, -3.37513568e-17,  9.21746554e-17],
        [-8.16184959e-17,  1.00000000e+00, -9.09799945e-17],
        [-1.35970237e-17, -4.67504265e-17,  1.00000000e+00]],

       [[ 1.00000000e+00, -1.41387766e-16,  1.31870745e-16],
        [-1.77703309e-17,  1.00000000e+00,  1.32077957e-16],
        [ 5.24172242e-17, -2.38113165e-16,  1.00000000e+00]],

       [[ 1.00000000e+00,  6.29676652e-17, -1.56693841e-16],
        [ 1.51418574e-16,  1.00000000e+00,  2.55858374e-16],
        [ 2.30220785e-17,  5.43123274e-17,  1.00000000e+00]]])

#### numpy.linalg.solve
- Ax = B 형태의 선형대수식 솔루션을 제공하는 함수
- 예) 
  - x와 y의 합: 25
  - 2x와 4y의 합: 64
  - $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix}=\begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [27]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

[18.  7.]


In [28]:
np.allclose(A@x, B)       # 두 수를 비교함

True