In [6]:
import numpy as np
import matplotlib.pyplot as plt

#### np.array 함수로 생성하기

In [11]:
x = np.array([1, 2, 3, 4])
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])      # 2행 3열의 행렬 생성 
print(y)
print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arrange 함수로 생성하기


In [13]:
np.arange(10)         # ndarray 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1, 11)     # python의 range()와 비슷한 기능임

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [22]:
# 5에서 100까지 간격 5인 ndarray 생성
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 ndarray 생성하기

In [25]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.ones((2, 3, 4))      # 3행 4열 행렬이 2개가 생성됨

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
np.zeros((2, 3, 4, 5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

#### np.empty, np.full로 ndarray 생성하기

In [35]:
np.empty((3, 4))        # 특정값으로 초기화되지 않음. 임의의 값으로 채워짐

array([[2.1408916e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [38]:
np.full((3, 4, 2), 8)

array([[[8, 8],
        [8, 8],
        [8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8],
        [8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8],
        [8, 8],
        [8, 8]]])

#### np.eye로 ndarray 생성하기
- 단위 행렬 생성
  - 단위 행렬은 행과 열의 수가 같음
  - 단위 행렬을 대각선은 1, 나머지는 0인 행렬임

In [45]:
np.eye(3)         # 3행 3열 행렬을 만들면서 대각선은 1로 생성함

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 ndarray 생성하기

In [59]:
np.linspace(3, 7, 3)      # 3부터 7사이 3개의 수 생성하는데 그 간격이 동일하게 만듬

array([3., 5., 7.])

In [61]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [64]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### reshape 함수 사용
  - ndarray의 형태, 차원을 바꾸기 위해 사용

In [77]:
x = np.arange(1, 16)
print(x)

x.shape     # 튜플로 표시됨. 1차원이라서 1개로만 표시됨 

x.reshape(3, 5)     # 1차원이 3행 5열의 행렬로 바뀜
x.reshape(5, 3)

x.reshape(5, 1, 3)  # 3차원으로 바뀜 

# x.reshape(5, 4)   # 데이터가 최소 20개가 필요함. 그러나 15개의 데이터만 존재하기 때문에 에러 발생함

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]]])