In [1]:
import numpy as np

#### 인덱싱
- 파이썬 리스트와 동일한 개념으로 사용
- ,를 사용하여 각 차원의 인덱스에 접근 가능

* 1차원 벡터 인덱싱

In [4]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
x[0]        # 첫번째 원소를 가져옴

0

In [9]:
x[-1]       # 마지막 원소를 가져옴

9

In [12]:
x[3]

3

In [14]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [17]:
x = np.arange(10).reshape((2, 5))
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
x[0]

array([0, 1, 2, 3, 4])

In [23]:
x[1]

array([5, 6, 7, 8, 9])

In [26]:
x[0, 2]

2

In [29]:
x[1, 3]

8

In [31]:
x[1, -1]

9

* 3차원 텐서 인덱싱

In [35]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [39]:
x[0]                  # 2차원 배열을 가져옴
x[1, 2]               # 크기가 3인 벡터를 가져옴 
x[0, 2, 2]            # 스칼라 값을 가져옴

8

#### 슬라이싱
- 리스트, 문자열 slicing과 동일한 개념으로 사용
- ,를 사용하여 각 차원별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [41]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [45]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 2차원 행렬 슬라이싱

In [52]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [54]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [55]:
x[:, :2]

array([[0, 1],
       [5, 6]])

In [58]:
x[0, 1:4]         # 인덱싱은 차원이 한차원 줄어듦(=> 1차원)

array([1, 2, 3])

In [61]:
x[:1, 1:4]        # 슬라이싱은 차원이 줄지 않음

array([[1, 2, 3]])

* 3차원 텐서 슬라이싱

In [64]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [73]:
x[:1, :2, :]          # 슬라이싱으로 가져옴(차원은 유지됨)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [77]:
x[0, :2]
x[0, :2, :]           # 인덱싱으로 가져올 때는 차원이 한차원 줄어듦 

array([[0, 1, 2],
       [3, 4, 5]])