In [2]:
import numpy as np

#### ravel, np.ravel()
- 다차원배열을 1차원으로 변경
- 'order' 파라미터
  - 'C' - row 우선 변경
  - 'F' - column 우선 변경

In [21]:
x = np.arange(15).reshape(3, 5)     # 행을 기준으로 값이 커짐
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
x.ravel()

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [9]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.ravel(x, order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.ravel(x, order='F')        # 값이 커지는 기준이 열임 

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [28]:
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [29]:
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [30]:
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


#### flatten
- 다차원 배열을 1차원으로 변경
- ravel과의 차이점
  - copy를 생성하여 변경함
  - 원본 데이터가 아닌 복사본을 반환
- 'order' 파라미터
  - 'C' - row 우선 변경
  - 'F' - column 우선 변경


In [33]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [35]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
t2= y.flatten()
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [40]:
t2[0] = 100
print(t2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [42]:
y.flatten(order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [44]:
y.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
x = np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [48]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### reshape() 함수
- array의 shape를 다른 차원으로 변경
- 주의할 점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
- 사례)
  - 이미지 데이터 벡터화
    - 이미지는 기본적으로 2차원 또는 3차원(RGB)이지만 데이터 트레이닝을 위해 1차원으로 변경하여 사용됨

In [49]:
x = np.arange(36)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [51]:
print(x.shape)        # 1차원임

(36,)


In [52]:
print(x.ndim)         # 차원

1


In [54]:
y = x.reshape(6, 6)     # 6행 6열로 바꿈
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [60]:
y = x.reshape(-1, 9)     # 4행 9열로 바꿈, 정확한 값을 모를 때는 -1을 주면 열이 정해져 있으니 행은 알아서 계산해줌 
print(y)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


In [62]:
y = x.reshape(6, -1)     # 정확한 값을 모를 때는 -1을 주면 열이 정해져 있으니 열은 알아서 계산해줌 
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [64]:
# x.reshape(6, 5)           # 크기가 맞지 않으면 에러남

In [66]:
y = x.reshape(6, 6)
print(y.shape)
print(y.ndim)

(6, 6)
2


In [67]:
y = x.reshape(-1, 2, 9)         # 나머지 2개가 고정되면 하나는 유추할 수 있으니 -1로 설정해도 됨 
print(y)
print(y.shape)
print(y.ndim)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]]

 [[18 19 20 21 22 23 24 25 26]
  [27 28 29 30 31 32 33 34 35]]]
(2, 2, 9)
3
