In [1]:
import numpy as np

#### numpy documentation
  - [numpy 공식 문서 링크](https://numpy.org/doc/stable/reference/)
  - numpy에서 제공되는 함수 등에 대한 문서

In [ ]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.80200755 0.38572188 0.72271876 0.48532687 0.92072765]
 [0.77074398 0.11451137 0.00183898 0.93541607 0.66086305]
 [0.64479935 0.81670967 0.00741482 0.62026987 0.84987957]]


In [4]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.72624402 0.94120969 0.02139558 0.27643932 0.02640367]
 [0.20051552 0.55451102 0.84072082 0.10938707 0.23129186]
 [0.76747457 0.45891648 0.2661814  0.99573062 0.79484896]]


#### 연산 함수
- add, substract, multiply, divide
- 연산하려는 ndarray의 구조가 같아야함

In [ ]:
np.add(x, y)

array([[ 0.29576857,  1.51631925,  2.06368969,  3.07257265,  4.56693572],
       [ 5.81925611,  6.17147827,  7.09679315,  8.95948846,  9.39274568],
       [10.3147849 , 11.64977703, 12.07401625, 13.36086252, 14.65171097]])

In [ ]:
np.subtract(x, y)

array([[-0.29576857,  0.48368075,  1.93631031,  2.92742735,  3.43306428],
       [ 4.18074389,  5.82852173,  6.90320685,  7.04051154,  8.60725432],
       [ 9.6852151 , 10.35022297, 11.92598375, 12.63913748, 13.34828903]])

In [ ]:
np.multiply(x, y)

array([[0.        , 0.51631925, 0.12737938, 0.21771796, 2.26774288],
       [4.09628055, 1.0288696 , 0.67755202, 7.67590766, 3.53471114],
       [3.14784904, 7.14754728, 0.88819497, 4.69121273, 9.12395354]])

In [ ]:
np.divide(x, y)

array([[  0.        ,   1.93678621,  31.40225779,  41.33788442,
          7.0554736 ],
       [  6.10309761,  34.9898569 ,  72.31917023,   8.33777618,
         22.91559247],
       [ 31.76772417,  16.92888416, 162.1265664 ,  36.0247999 ,
         21.48191561]])

In [ ]:
x + y

array([[ 0.29576857,  1.51631925,  2.06368969,  3.07257265,  4.56693572],
       [ 5.81925611,  6.17147827,  7.09679315,  8.95948846,  9.39274568],
       [10.3147849 , 11.64977703, 12.07401625, 13.36086252, 14.65171097]])

In [ ]:
x - y

array([[-0.29576857,  0.48368075,  1.93631031,  2.92742735,  3.43306428],
       [ 4.18074389,  5.82852173,  6.90320685,  7.04051154,  8.60725432],
       [ 9.6852151 , 10.35022297, 11.92598375, 12.63913748, 13.34828903]])

In [ ]:
x*y

array([[0.        , 0.51631925, 0.12737938, 0.21771796, 2.26774288],
       [4.09628055, 1.0288696 , 0.67755202, 7.67590766, 3.53471114],
       [3.14784904, 7.14754728, 0.88819497, 4.69121273, 9.12395354]])

In [ ]:
x/y

array([[  0.        ,   1.93678621,  31.40225779,  41.33788442,
          7.0554736 ],
       [  6.10309761,  34.9898569 ,  72.31917023,   8.33777618,
         22.91559247],
       [ 31.76772417,  16.92888416, 162.1265664 ,  36.0247999 ,
         21.48191561]])

#### 통계 함수
- 평균, 분산, 중앙, 최대, 최소값 등 통계 관련된 함수가 내장됨

In [5]:
print(y)

[[0.72624402 0.94120969 0.02139558 0.27643932 0.02640367]
 [0.20051552 0.55451102 0.84072082 0.10938707 0.23129186]
 [0.76747457 0.45891648 0.2661814  0.99573062 0.79484896]]


In [ ]:
np.mean(y)

0.40041328012727406

In [ ]:
y.mean()

0.40041328012727406

In [ ]:
np.max(y)

0.9594884572435106

In [6]:
np.argmax(y)      # 가장 큰 값의 인덱스를 가져옴

13

In [10]:
np.var(y), np.median(y), np.std(y)          # 분산, 중앙값, 표준편차 계산 

(0.10918345072576757, 0.4589164809063673, 0.3304291916973553)

#### 집계 함수
- 합(sum), 누적합계(cumsum) 등등 계산 가능

In [11]:
y

array([[0.72624402, 0.94120969, 0.02139558, 0.27643932, 0.02640367],
       [0.20051552, 0.55451102, 0.84072082, 0.10938707, 0.23129186],
       [0.76747457, 0.45891648, 0.2661814 , 0.99573062, 0.79484896]])

In [12]:
sum(y)

array([1.69423411, 1.95463719, 1.1282978 , 1.38155701, 1.05254449])

In [17]:
np.sum(y, axis=0)         # 축을 따라 합을 구함(행)

array([1.69423411, 1.95463719, 1.1282978 , 1.38155701, 1.05254449])

In [18]:
np.sum(y, axis=1)         # 축을 따라 합을 구함(열)

array([1.99169227, 1.93642629, 3.28315203])

In [22]:
np.sum(y, axis=None)      # None이면 전체의 합을 구함 

7.211270592967458

In [23]:
np.cumsum(y)

array([0.72624402, 1.66745371, 1.68884929, 1.9652886 , 1.99169227,
       2.19220779, 2.74671881, 3.58743963, 3.69682669, 3.92811856,
       4.69559313, 5.15450961, 5.42069101, 6.41642163, 7.21127059])

#### any, all 함수
- any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [24]:
z = np.random.randn(10)
print(z)

[ 0.20927577 -0.08038484 -0.17159104 -1.20954841 -0.14929278  0.74997727
 -0.02802779 -0.23179101 -1.05793912 -1.98664077]


In [25]:
z > 0

array([ True, False, False, False, False,  True, False, False, False,
       False])

In [27]:
np.any(z>0)

True

In [29]:
np.all(z>0)         # loop가 필요없음

False

In [31]:
np.all(z != 0)

True

#### where 함수
- 조건에 따라 선별적으로 값을 선택 가능
- 예) 음수인 경우는 0, 나머지는 그대로 값을 쓰는 경우

In [32]:
z = np.random.randn(10)
print(z)

[-0.1354864   0.69431242  0.87772261  0.51391321 -0.54845887 -1.82693574
 -0.14035132  0.60949144 -0.55605341  0.89954939]


In [33]:
np.where(z > 0, z, 0)

array([0.        , 0.69431242, 0.87772261, 0.51391321, 0.        ,
       0.        , 0.        , 0.60949144, 0.        , 0.89954939])