In [1]:
import numpy as np

#### axis란?
- 몇몇 함수에는 axis keyword 파라미터가 존재
- axis값이 없는 경우에는 전체 데이터에 대해 적용
- axis값이 있는 경우에는, 해당 axis를 따라 연산 적용

* axis를 파라미터로 갖는 함수
- 거의 대부분의 연산 함수들이 axis 파라미터를 사용
- 이 경우, 해당 값이 주어졌을 때, 해당 axis를 따라 연산이 적용
- 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
- 예) np.sum, np.mean, np.any 등등

In [2]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


* 1차원 데이터에 적용하기

In [4]:
np.sum(x)           # axis으 기본값은 None

105

In [8]:
np.sum(x, axis=0)     # 축이 한개이므로 그냥 해당 축을 따라 계산을 하라 

105

In [10]:
# np.sum(x, axis=1)     # 축이 한개이므로 1을 주면 범위를 벗어나게 됨. 1을 갖으려면 최소한2차원이 되어야함

* 행렬 데이터에 적용하기


In [13]:
y = x.reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
np.sum(y, axis=0)     # 가로는 행이 증가하는 방향(0). 세로는 열이 증가하는 방향(1)
np.sum(y, axis=1)

array([10, 35, 60])

* 3차원 텐서에 적용하기

In [18]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [20]:
np.sum(z)

630

In [22]:
np.sum(z, axis=0)     # 0번째 따라서 압축을 시킨것임, 3차원 각상자를 포갠것임, 0번째를 없앴기때문에 (4, 3)만 남음

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [24]:
np.sum(z, axis=1)     # 1번째 따라서 압축을 시킨것임, 1번째를 없앴기때문에 (3, 3)만 남음

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [26]:
np.sum(z, axis=2)     # 2번째 따라서 압축을 시킨것임, 2번째를 없앴기때문에 (3, 4)만 남음

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [33]:
np.sum(z, axis=-1)    # np.sum(z, axis=2)과 결과가 동일함, 축에 대해서 음수를 지원함. 가능하면 양수로 사용할 것을 권장함 
np.sum(z, axis=-2)    # np.sum(z, axis=1)과 결과가 동일함 
np.sum(z, axis=-3)    # np.sum(z, axis=0)과 결과가 동일함 

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

* axis의 값이 튜플일 경우
- 해당 튜플에 명시된 모든 axis에 대해 연산

In [34]:
np.sum(z, axis=(0, 2))      # 0번째 2번째 축을 따라 동시에 합하라. 두 축을 사용하므로 4만 남음

array([117, 144, 171, 198])