In [1]:
import numpy as np

#### 브로드캐스팅
- Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
- 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드캐스팅(Shape을 맞춤) 후 진행

### 브로드캐스팅 Rule
  - [공식문서](https://numpy.org/doc/stable/_images/broadcasting_2.png)
  - 뒷 차원에서부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

* Shape이 같은 경우 연산

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.randint(0, 15, 15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6 13  0  6  1]
 [ 6  6 14  2 12]
 [12 14  0  8  1]]


In [4]:
x + y

array([[ 6, 14,  2,  9,  5],
       [11, 12, 21, 10, 21],
       [22, 25, 12, 21, 15]])

* Scalar(상수)와의 연산

In [6]:
x + 2         # 모든 원소에 연산이 됨

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [7]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [8]:
x ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

* Shape이 다른 경우 연산

In [9]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]


In [10]:
a + b       # b가 stretch되어 연산이 가능해짐

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [13]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)                   # 1행 3열짜리 벡터
c = np.arange(1000, 1004)                 # 1행 4열짜리 벡터 
print(a)
print(b)
print(c)

print(a.shape)
print(b.shape)
print(c.shape)                            
# 브로드캐스팅은 뒷 차원에서부터 비교함 
# (4, 3)와 (3,)은 뒷 차원이 같음
# (4, 3)와 (4,)은 뒷 차원이 다름

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
(4, 3)
(3,)
(4,)


In [15]:
# a + c

In [18]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)                   # 벡터
c = np.arange(1000, 1004)                 # 벡터 
d = b.reshape(1, 3)                       # 행렬 
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(d)

(4, 3)
(3,)
(4,)
(1, 3)
[[100 101 102]]


In [19]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [20]:
e = c.reshape(4,1)
a + e

array([[1000, 1001, 1002],
       [1004, 1005, 1006],
       [1008, 1009, 1010],
       [1012, 1013, 1014]])