#### Boolean indexing
- ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링
- 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1, 100, size=10)
print(x)

[12 73 35 68 97  7 23 17 25 47]


In [6]:
even_mask = x % 2 == 0
print(even_mask)

[ True False False  True False False False False False False]


* bool 리스트를 인덱스로 전달

In [7]:
x[even_mask]

array([12, 68])

In [9]:
x[x%2==0]

array([12, 68])

In [11]:
x[x>50]

array([73, 68, 97])

#### 다중조건 사용하기
- 파이썬의 논리 연산자 and, or, not 키워드 사용 불가
- &, | 사용

In [18]:
x % 2 == 0
x > 80

x[(x % 2 == 0) & (x > 50)]

array([68])

In [20]:
x < 30
x > 50

x[(x < 30) | (x > 50)]

array([12, 73, 68, 97,  7, 23, 17, 25])

예) 2023년 7월 서울 평균 기온 데이터 
  - 평균기온이 25도를 넘는 날의 수는 몇일인가?
  - 평균기온이 25도를 넘는 날의 평균 기온은 몇도인가?

In [22]:
tmp = np.array(
    [23.9, 24.4, 26.0, 28.1, 27.6, 29.7, 26.1, 25.0, 24.6, 26.9, 27.1, 28.3,
     24.9, 26.3, 23.8, 29.3, 27.6, 21.0, 26.4, 28.0, 26.4, 24.5, 23.9, 23.9, 
     26.3, 25.9, 28.4, 27.5, 25.8, 24.9, 26.3]
)

len(tmp)

31

In [25]:
tmp[tmp>25.0]

array([26. , 28.1, 27.6, 29.7, 26.1, 26.9, 27.1, 28.3, 26.3, 29.3, 27.6,
       26.4, 28. , 26.4, 26.3, 25.9, 28.4, 27.5, 25.8, 26.3])

In [27]:
len(tmp[tmp>25.0])

20

In [28]:
tmp[tmp>25.0].mean()

27.199999999999996

In [35]:
len(tmp[tmp>25.0])

20

In [36]:
np.sum(tmp>25.0)            # tmp>25.0 조건에 맞는 개수를 반환

20

In [37]:
np.sum(tmp[tmp>25.0])       # tmp에서 tmp>25.0 인덱싱의 값들 합을 반환 

543.9999999999999